# Generated by Django 4.1.5 on 2023-01-11 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=25)),
                ('symbol', models.CharField(max_length=20)),
                ('rate', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.currency'),
        ),
    ]
