# Generated by Django 4.1.5 on 2023-01-19 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_currency_package_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='billing_model',
            field=models.CharField(choices=[('flat_rate', 'Flat Rate'), ('per_user', 'Per User'), ('per_user_tier', 'Per User Tiers'), ('storage_tier', 'Storage Tiers'), ('pay_as_you_go', 'Pay As You Go'), ('per_activer_user', 'Per Active User'), ('feature_based', 'Feature Based Tiers'), ('freemium', 'Freemium')], default='flat_rate', max_length=30),
        ),
        migrations.AddField(
            model_name='package',
            name='billing_unit_limit',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.currency'),
        ),
        migrations.AlterField(
            model_name='package',
            name='rate',
            field=models.FloatField(help_text='package billing rate'),
        ),
    ]
