# Generated by Django 4.1.5 on 2023-02-11 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_delete_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='package',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.service'),
        ),
        migrations.AlterField(
            model_name='package',
            name='billing_model',
            field=models.CharField(choices=[('flat_rate', 'Flat Rate'), ('per_user', 'Per User'), ('per_user_tier', 'Per User Tiers'), ('storage_tier', 'Storage Tiers'), ('pay_as_you_go', 'Pay As You Go'), ('per_active_user', 'Per Active User'), ('feature_based', 'Feature Based Tiers'), ('freemium', 'Freemium')], default='flat_rate', max_length=30),
        ),
    ]
