VALIDITY_STATUS_PENDING = "pending"
VALIDITY_STATUS_ACTIVE = "active"
VALIDITY_STATUS_CANCELED = "cancelled"
VALIDITY_STATUS_EXPIRED = "expired"


VALIDITY_STATUS_CHOICES = (
    (VALIDITY_STATUS_PENDING, "Pending"),
    (VALIDITY_STATUS_ACTIVE, "Active"),
    (VALIDITY_STATUS_CANCELED, "Cancelled"),
    (VALIDITY_STATUS_EXPIRED, "Expired")
)


VALIDITY_UNIT_HOURS = "hour"
VALIDITY_UNIT_DAYS = "day"

VALIDITY_UNIT_CHOICES = (
    (VALIDITY_UNIT_DAYS, "Days"),
    (VALIDITY_UNIT_HOURS, "Hours")
)

SUBSCRIBER_TYPE_INDIVIDUAL = "individual"
SUBSCRIBER_TYPE_NON_INDIVIDUAL = "non_individual"

SUSCRIBER_TYPE_CHOICES = (
    (SUBSCRIBER_TYPE_INDIVIDUAL, "Individual"),
    (SUBSCRIBER_TYPE_NON_INDIVIDUAL, "Non Individual")
)

BILLING_MODEL_FLAT_RATE = "flat_rate"
BILLING_MODEL_PER_USER = "per_user"
BILLING_MODEL_PER_USER_TIERS = "per_user_tier"
BILLING_MODEL_STORAGE_TIERS = "storage_tier"
BILLING_MODEL_PAYG = "pay_as_you_go"
BILLING_MODEL_PAU = "per_active_user"
BILLING_MODEL_FEATURE_BASED = "feature_based"
BILLING_MODEL_FREEMIUM = "freemium"


BILLING_MODEL_CHOICES = (
    (BILLING_MODEL_FLAT_RATE, "Flat Rate"),
    (BILLING_MODEL_PER_USER, "Per User"),
    (BILLING_MODEL_PER_USER_TIERS, "Per User Tiers"),
    (BILLING_MODEL_STORAGE_TIERS, "Storage Tiers"),
    (BILLING_MODEL_PAYG, "Pay As You Go"),
    (BILLING_MODEL_PAU, "Per Active User"),
    (BILLING_MODEL_FEATURE_BASED, "Feature Based Tiers"),
    (BILLING_MODEL_FREEMIUM, "Freemium")
)

INVOICE_TYPE_SERVICE = "service"
INVOICE_TYPE_SUBSCRIPTION = "subscription"

INVOICE_TYPE_CHOICES = (
    (INVOICE_TYPE_SERVICE, "Service Payment"),
    (INVOICE_TYPE_SUBSCRIPTION, "Subscription Payment")
)

PAYMENT_MERCHANT_AIRTEL = "airtel"
PAYMENT_MERCHANT_MTN = "mtn"
