# Generated by Django 4.1.5 on 2023-01-19 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('ref', models.CharField(max_length=30, unique=True)),
                ('extras', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='subcription',
            old_name='subscriber_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='subcription',
            old_name='subscriber_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='subcription',
            old_name='susbcriber_extras',
            new_name='extras',
        ),
        migrations.RenameField(
            model_name='subcription',
            old_name='subscriber_ref',
            new_name='ref',
        ),
        migrations.AddField(
            model_name='subcription',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('non_individual', 'Non Individual')], default='individual', max_length=25),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('ref', models.CharField(max_length=30, unique=True)),
                ('extras', models.JSONField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_clients', to='subscriptions.company', to_field='ref')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
