# Generated by Django 4.1.5 on 2023-02-11 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_alter_package_options_alter_period_options_and_more'),
        ('subscriptions', '0003_alter_company_options_client_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('ref', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('extras', models.JSONField(help_text='subscribers details')),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('non_individual', 'Non Individual')], default='non_individual', max_length=25)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=25)),
                ('current_invoicing_start_date', models.DateTimeField(blank=True, null=True)),
                ('current_invoicing_end_date', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_subscriptions', to='packages.package')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-created_at',)},
        ),
        migrations.DeleteModel(
            name='Subcription',
        ),
    ]
