# Generated by Django 4.1.5 on 2023-02-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription_alter_client_options_delete_subcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_activity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
